### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by alimasilva2018** [HashLoad/horse-logger-provider-logfile#10]
Foi criado um exemplo console em anexo, é necessário estar com IsConsole := False. Não é necessário haver chamada ao endpoint basta  abrir e fechar o console. Tentei fazer downgrade ate a versão 1.0.3 mas continua se reproduzinfo.

Usando o MadExcept neste exemplo tem as saidas.
allocation number: 1738
program up time: 110 ms
type: THorseLoggerLogFileConfig
address: $6834690
size: 20
access rights: read/write

main thread ($1abc):
7b2e91f7 madExcept32.dll    madExceptDbg                   1749 GetMemCallback
005d6fd0 HorseTesteLeak.exe System                         4949 @GetMem
005d997e HorseTesteLeak.exe System                        18306 TObject.NewInstance
005da06b HorseTesteLeak.exe System                        19635 @ClassCreate
008898d1 HorseTesteLeak.exe Horse.Logger.Provider.LogFile   205 THorseLoggerLogFileConfig.Create
005d703f HorseTesteLeak.exe System                         5141 @ReallocMem
005dec0c HorseTesteLeak.exe System                        36819 DynArraySetLength
005d9d7e HorseTesteLeak.exe System                        18878 @IsClass
006ebd7a HorseTesteLeak.exe System.Classes                 6086 GetDesigner
006ebe50 HorseTesteLeak.exe System.Classes                 6131 NotifyDesigner
006ebe77 HorseTesteLeak.exe System.Classes                 6134 NotifyDesigner
005da0d9 HorseTesteLeak.exe System                        19684 @AfterConstruction
005d6fd0 HorseTesteLeak.exe System                         4949 @GetMem
005da0d9 HorseTesteLeak.exe System                        19684 @AfterConstruction
00889c68 HorseTesteLeak.exe Horse.Logger.Provider.LogFile   239 THorseLoggerLogFileConfig.New
0089522a HorseTesteLeak.exe HorseTesteLeak                   25 initialization
008952f1 HorseTesteLeak.exe HorseTesteLeak                   45 initialization
7562fcc7 KERNEL32.DLL                                           BaseThreadInitThunk

memory dump: 
06834690  2c 8c 88 00 84 65 2e 04 - 44 90 2d 04 b4 05 2d 04  ,....e..D.-...-.
068346a0  00 00 00 00               
![error_log](https://github.com/HashLoad/horse-logger-provider-logfile/assets/34888072/262717a8-8335-4cd2-9c0a-540890a00956)
[LeakLog.zip](https://github.com/HashLoad/horse-logger-provider-logfile/files/13029588/LeakLog.zip)

**Comment by viniciussanchez** [comment]
O @CarlosHe observou que o problema veio por ter criado a classe de configuração mas não ter usado ela no provider:

![image](https://github.com/HashLoad/horse-logger-provider-logfile/assets/16382981/2287de41-4b8a-454c-8a9c-e97c5dbc2125)
