### ISSUE TITLE
Não salva todas as requisições no log

### ISSUE THREAD

**Issue by ednergassen** [HashLoad/horse-logger-provider-logfile#11]
Boa tarde!

Estou utilizando o horse-logger-provider-logfile, para salvar log das requisições. Contudo, o mesmo não está salvando todas as requisições no log.

Efetuei 400 requisições e apenas 270 são salvas no log.

Esse framework tem alguma limitação?

**Comment by viniciussanchez** [comment]
Boa tarde... talvez tenha pelo fato de ter que gerenciar o acesso concorrente a um arquivo texto, por meio de várias threads... porém o @CarlosHe fez um esquema de fila dentro do middleware... talvez possa ter alguma falha, ou talvez você disparou as 400 requisições simultâneas e pelo fato de ser uma fila, nem todas terminaram de ser escritas quando você abriu o arquivo... precisava analisar certinho

**Comment by ednergassen** [comment]
> ou talvez você disparou as 400 requisições simultâneas e pelo fato de ser uma fila, nem todas terminaram de ser escritas quando você abriu o arquivo

Mesmo abrindo o arquivo de log depois de um determinado tempo, o mesmo não se alterou em nada. Vou analisar...

Obrigado!

**Comment by viniciussanchez** [comment]
Boa tarde, chegou a alguma conclusão?
