### ISSUE TITLE
Criar o diretório definido

### ISSUE THREAD

**Issue by tiagoistuque** [HashLoad/horse-logger-provider-logfile#2]
O middleware poderia tentar criar automaticamente o diretório definido em THorseLoggerProviderLogFile.SetDir caso não exista.

**Comment by viniciussanchez** [comment]
Legal.... se puder contribuir mandando a alteração do código para que isso funcione seria bom. Caso contrário, já agradeço pela ideia.

**Comment by tiagoistuque** [comment]
> Legal.... se puder contribuir mandando a alteração do código para que isso funcione seria bom. Caso contrário, já agradeço pela ideia.

Sim, posso fazer, é bem simples. Assim que estiver implementado envio um pull request. Obrigado!

**Comment by viniciussanchez** [comment]
vlw
