### ISSUE TITLE
custom directory of log not works

### ISSUE THREAD

**Issue by acarlomagno** [HashLoad/horse-logger-provider-logfile#7]
Hello

I noticed that if I configure a directory for the log file ... it seems that when it goes to record the log it resets the value of the directory with that of the .exe folder
Debugging, go through here twice and path is reset.

constructor THorseLoggerLogFileConfig.Create;
begin
   FLogFormat: = DEFAULT_HORSE_LOG_FORMAT;
   FDir: = ExtractFileDir (ParamStr (0));
end;

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/220909698-8d0f6a02-0fff-4471-b412-bc184bda0e6b.png)
![image](https://user-images.githubusercontent.com/16382981/220911658-aabbb43b-a946-44ad-8db2-bded6bf85a5c.png)
