### ISSUE TITLE
Compatibilidade Linux

### ISSUE THREAD

**Issue by PlimSistemas** [HashLoad/horse-logger-provider-logfile#9]
Remover unit desnecessária que impede compilação para Linux
**unit: Winapi.Windows**

**Comment by PlimSistemas** [comment]
Na verdade quando o sistema é  **Windows** precisa da **unit Winapi.Windows**,
mas quando é Linux não há necessidade dessa unit, e o projeto compila normalmente.

Sendo assim basta adicionar a diretiva de compilação

```
{$IFDEF MSWINDOWS}
  Winapi.Windows
{$ENDIF }
```

**Comment by viniciussanchez** [comment]
Esse problema já foi ajustado... pode verificar usando a ultima versao disponibilizada?
